# .sops.yaml
# sops configuration file
# Define which keys can decrypt which files

# Keys configuration
keys:
  # Age keys (add your public key here after generating)
  # Generate with: age-keygen -o /var/lib/sops-nix/key.txt
  # Get public key with: age-keygen -y /var/lib/sops-nix/key.txt
  - &admin age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  # Default rule for all yaml files in secrets/
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin

  # Host-specific secrets (if needed)
  # - path_regex: secrets/framework\.yaml$
  #   key_groups:
  #     - age:
  #         - *framework_key
